version: '2'

services:
  app:
    image: 'core:latest'
    build:
      context: .
    container_name: app
    links:
      - db
    ports:
      - "5555:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/core_dev
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=273849
      - SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_LOB_NON_CONTEXTUAL_CREATION=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    container_name: db
    volumes:
      - ./var/pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=273849

